rtl/barrett_reduce.v
rtl/montgomery_reduce.v
rtl/shuffle_net.v
rtl/ae_regfile.v
rtl/useq_core.v
rtl/useq_rom.v
rtl/twiddle_rom.v
rtl/scheme_rom.v
rtl/ntt_stage_ctrl.v
rtl/reconfig_ae.v
rtl/reconfig_ae_array.v
rtl/reconfig_ae_rf.v
rtl/reconfig_ntt_operator.v
rtl/reconfig_ntt_pipeline.v
rtl/falcon_f64_add.v
rtl/falcon_f64_mul.v
rtl/reconfig_fe_f64.v
rtl/reconfig_fe_f64_pipe.v
rtl/reconfig_fe_f64_array.v
rtl/reconfig_fe_f64_pipe_array.v
rtl/reconfig_fft_f64_operator.v
rtl/reconfig_fft_f64_pipe_operator.v
rtl/reconfig_fe_f64_shared_array.v
rtl/reconfig_fft_f64_shared_operator.v
rtl/vpu_fe_unit.v
rtl/vpu_fe_exu_adapter.v
rtl/falcon_fft_addr_gen.v
rtl/falcon_fft_stage_ctrl.v
rtl/falcon_fft_batch_exu.v
rtl/falcon_fft_task_engine.v
rtl/falcon_fft_local_buffer.v
rtl/falcon_fft_twiddle_cache.v
rtl/falcon_fft_buffered_engine.v
rtl/spuv3_vpu_fe_mem_pack.v
rtl/spuv3_vpu_fe_f64_wrap.v
