#!/usr/bin/env python3
"""
Comprehensive Falcon FFT/IFFT Golden Verification Suite
=========================================================

Pre-simulation verification: reads golden vectors generated by
falcon_fft_golden.py and simulates the RTL butterfly operator
(reconfig_fe_f64) to verify lane-by-lane correctness BEFORE
running Verilog simulation.

Key verification: for IFFT, the golden model outputs conj(GM) as the
twiddle. The RTL GS butterfly does y1 = w * (a-b) with NO internal conj.
So feeding w = conj(GM) into the RTL yields the correct Falcon iFFT result.

Test matrix:
  - logN: 9 (Falcon-512), 10 (Falcon-1024)
  - mode: FFT (CT), IFFT (GS)
  - input types: impulse, ramp, random, falcon_poly, all_zeros, single_spike
  - lane patterns: all-5, partial (3-of-5, 1-of-5)

Usage:
  python verify_fft_golden.py                    # quick: N=512, both modes, random
  python verify_fft_golden.py --full             # full matrix
  python verify_fft_golden.py --logn 9 --mode fft
"""

import sys
import os
import argparse
import struct
import math
from typing import List, Tuple, Optional

# Add parent dir for falcon_fft_golden import
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from falcon_fft_golden import (
    generate_gm_table,
    falcon_fft, falcon_ifft,
    extract_fft_stage_vectors, extract_ifft_stage_vectors,
    rtl_ct_butterfly, rtl_gs_butterfly,
    make_test_input_impulse, make_test_input_ramp,
    make_test_input_random, make_test_input_falcon_poly,
    f64_bits, f64_to_hex, hex_to_f64,
    ButterflyVector,
)

# ============================================================================
# Additional test input generators
# ============================================================================

def make_test_input_all_zeros(logn: int) -> List[float]:
    """All zeros — degenerate but valid input."""
    return [0.0] * (1 << logn)


def make_test_input_single_spike(logn: int, pos: int = 0, value: float = 1.0) -> List[float]:
    """Single non-zero value at position `pos`."""
    n = 1 << logn
    f = [0.0] * n
    if 0 <= pos < n:
        f[pos] = value
    return f


def make_test_input_alternating(logn: int) -> List[float]:
    """Alternating +/- 1.0 pattern."""
    n = 1 << logn
    return [1.0 if i % 2 == 0 else -1.0 for i in range(n)]


def make_test_input_large_values(logn: int) -> List[float]:
    """Large magnitude values near 1e300."""
    n = 1 << logn
    import random
    rng = random.Random(0xB16)
    return [rng.uniform(1e200, 1e300) * (1 if rng.random() > 0.5 else -1)
            for _ in range(n)]


def make_test_input_tiny_values(logn: int) -> List[float]:
    """Tiny values near 1e-300 (denormal range edge)."""
    n = 1 << logn
    import random
    rng = random.Random(0x71)
    return [rng.uniform(1e-300, 1e-290) * (1 if rng.random() > 0.5 else -1)
            for _ in range(n)]


# ============================================================================
# Verification core
# ============================================================================

class VerifyResult:
    """Result of verifying one butterfly vector."""
    def __init__(self, vec: ButterflyVector, inverse: bool):
        self.vec = vec
        self.inverse = inverse

        # Simulate RTL butterfly
        if inverse:
            (gy0_re, gy0_im), (gy1_re, gy1_im) = rtl_gs_butterfly(
                vec.a_re, vec.a_im, vec.b_re, vec.b_im,
                vec.w_re, vec.w_im)
        else:
            (gy0_re, gy0_im), (gy1_re, gy1_im) = rtl_ct_butterfly(
                vec.a_re, vec.a_im, vec.b_re, vec.b_im,
                vec.w_re, vec.w_im)

        self.gy0_re = gy0_re; self.gy0_im = gy0_im
        self.gy1_re = gy1_re; self.gy1_im = gy1_im

        # Compare against golden (bit-exact IEEE-754 comparison)
        self.y0_re_match = f64_bits(gy0_re) == f64_bits(vec.y0_re)
        self.y0_im_match = f64_bits(gy0_im) == f64_bits(vec.y0_im)
        self.y1_re_match = f64_bits(gy1_re) == f64_bits(vec.y1_re)
        self.y1_im_match = f64_bits(gy1_im) == f64_bits(vec.y1_im)

        self.passed = (self.y0_re_match and self.y0_im_match and
                       self.y1_re_match and self.y1_im_match)

        # Relative error for diagnostics
        def rel_err(a, b):
            denom = max(1.0, abs(a), abs(b))
            return abs(a - b) / denom if denom > 0 else (0.0 if a == b else float('inf'))

        self.err_y0_re = rel_err(gy0_re, vec.y0_re)
        self.err_y0_im = rel_err(gy0_im, vec.y0_im)
        self.err_y1_re = rel_err(gy1_re, vec.y1_re)
        self.err_y1_im = rel_err(gy1_im, vec.y1_im)

    def max_err(self) -> float:
        return max(self.err_y0_re, self.err_y0_im,
                   self.err_y1_re, self.err_y1_im)


def verify_stage_vectors(vectors: List[ButterflyVector],
                          inverse: bool) -> Tuple[int, int, float]:
    """
    Verify all butterfly vectors for one stage.
    Returns (passed, total, max_error).
    """
    passed = 0
    max_err = 0.0
    for v in vectors:
        r = VerifyResult(v, inverse)
        if r.passed:
            passed += 1
        max_err = max(max_err, r.max_err())
    return passed, len(vectors), max_err


def verify_full_fft(logn: int, gm: List[Tuple[float, float]],
                     test_input: List[float], inverse: bool,
                     lanes: int = 5, verbose: bool = False
                     ) -> dict:
    """
    Full-stage verification: run FFT/IFFT, extract stage vectors,
    verify each butterfly.

    Returns dict with per-stage statistics.
    """
    label = 'IFFT' if inverse else 'FFT'
    n = 1 << logn
    n_stages = logn - 1

    # Run reference FFT/IFFT
    f_work = list(test_input)
    if inverse:
        stage_snapshots = falcon_ifft(f_work, logn, gm)
    else:
        stage_snapshots = falcon_fft(f_work, logn, gm)

    total_passed = 0
    total_pairs = 0
    stage_results = []

    for s in range(n_stages):
        f_before = test_input if s == 0 else stage_snapshots[s - 1]

        if inverse:
            vecs = extract_ifft_stage_vectors(f_before, logn, gm, s, lanes)
        else:
            vecs = extract_fft_stage_vectors(f_before, logn, gm, s, lanes)

        passed, n_pairs, max_err = verify_stage_vectors(vecs, inverse)
        total_passed += passed
        total_pairs += n_pairs

        stage_results.append({
            'stage': s, 'pairs': n_pairs, 'passed': passed,
            'max_err': max_err, 'ok': passed == n_pairs
        })

        if verbose:
            status = 'OK' if passed == n_pairs else f'FAIL ({n_pairs-passed} mismatches)'
            print(f"    Stage {s:2d}: {passed:4d}/{n_pairs:4d} passed  "
                  f"max_err={max_err:.2e}  {status}")

    return {
        'label': label, 'logn': logn, 'inverse': inverse,
        'stages': stage_results,
        'total_passed': total_passed, 'total_pairs': total_pairs,
        'all_ok': total_passed == total_pairs,
    }


# ============================================================================
# Test case runner
# ============================================================================

TEST_MATRIX = {
    'impulse':      make_test_input_impulse,
    'ramp':         make_test_input_ramp,
    'random':       make_test_input_random,
    'falcon_poly':  make_test_input_falcon_poly,
    'all_zeros':    make_test_input_all_zeros,
    'alternating':  make_test_input_alternating,
    'large_values': make_test_input_large_values,
    'tiny_values':  make_test_input_tiny_values,
}

# Additional single-spike cases at various positions
SPIKE_CASES = [
    ('spike_pos0',     0,  1.0),
    ('spike_pos1',     1,  1.0),
    ('spike_pos127', 127,  1.0),
    ('spike_pos255', 255,  1.0),
    ('spike_neg',      0, -1.0),
    ('spike_large',    0,  1e200),
    ('spike_tiny',     0,  1e-200),
]


def run_test_suite(logn_values: List[int], modes: List[str],
                   input_types: List[str], lanes: int = 5,
                   verbose: bool = False) -> dict:
    """
    Run full verification suite across the test matrix.

    Returns summary dict.
    """
    all_results = []
    total_ops = 0
    total_passed = 0

    for logn in logn_values:
        gm = generate_gm_table(logn)
        n = 1 << logn

        for mode in modes:
            inverse = (mode == 'ifft')

            for itype in input_types:
                if itype.startswith('spike_'):
                    continue  # handled separately

                test_input = TEST_MATRIX[itype](logn)

                if verbose:
                    print(f"\n  [{mode.upper()}] logN={logn} N={n} input={itype}")

                result = verify_full_fft(logn, gm, test_input, inverse,
                                         lanes=lanes, verbose=verbose)
                all_results.append(result)
                total_ops += result['total_pairs']
                total_passed += result['total_passed']

            # Add spike test cases
            for spike_name, pos, val in SPIKE_CASES:
                test_input = make_test_input_single_spike(logn, pos, val)
                if verbose:
                    print(f"\n  [{mode.upper()}] logN={logn} N={n} input={spike_name}")

                result = verify_full_fft(logn, gm, test_input, inverse,
                                         lanes=lanes, verbose=verbose)
                all_results.append(result)
                total_ops += result['total_pairs']
                total_passed += result['total_passed']

    return {
        'results': all_results,
        'total_ops': total_ops,
        'total_passed': total_passed,
        'all_pass': total_passed == total_ops,
    }


# ============================================================================
# Specific RTL GS mode IFFT conj(w) verification
# ============================================================================

def verify_ifft_conj_twiddle(logn: int, verbose: bool = True):
    """
    Explicitly verify that feeding conj(GM) as w to RTL GS mode
    produces the correct Falcon iFFT output.

    This is the critical verification: Falcon iFFT uses conj(GM)*(a-b),
    RTL GS mode uses w*(a-b). For them to match, w must be conj(GM).
    """
    gm = generate_gm_table(logn)
    n = 1 << logn
    hn = n >> 1

    # Use a non-trivial test input
    import random
    rng = random.Random(0xC01)
    test_input = [rng.uniform(-10.0, 10.0) for _ in range(n)]

    # Run reference iFFT
    f_ref = list(test_input)
    ref_snapshots = falcon_ifft(f_ref, logn, gm)

    if verbose:
        print(f"\n{'='*70}")
        print(f"  IFFT conj(w) Verification -- logN={logn}, N={n}")
        print(f"{'='*70}")

    n_stages = logn - 1
    total_ok = 0
    total_check = 0

    for s in range(n_stages):
        f_before = test_input if s == 0 else ref_snapshots[s - 1]

        # Extract butterflies: the golden uses CONJ(GM) as w
        vecs = extract_ifft_stage_vectors(f_before, logn, gm, s, lanes=5)

        mismatches = []
        for v in vecs:
            total_check += 1

            # Verify: RTL GS butterfly with w (which already = conj(GM))
            (y0_re, y0_im), (y1_re, y1_im) = rtl_gs_butterfly(
                v.a_re, v.a_im, v.b_re, v.b_im, v.w_re, v.w_im)

            # Compare against golden (which was computed by falcon_ifft)
            y0_ok = (f64_bits(y0_re) == f64_bits(v.y0_re) and
                     f64_bits(y0_im) == f64_bits(v.y0_im))
            y1_ok = (f64_bits(y1_re) == f64_bits(v.y1_re) and
                     f64_bits(y1_im) == f64_bits(v.y1_im))

            if y0_ok and y1_ok:
                total_ok += 1
            else:
                mismatches.append((v.pair_idx, y0_ok, y1_ok))

        if verbose and mismatches:
            print(f"  Stage {s}: {len(mismatches)} mismatches out of {len(vecs)}")
            for pair_idx, y0_ok, y1_ok in mismatches[:5]:
                parts = []
                if not y0_ok: parts.append('y0')
                if not y1_ok: parts.append('y1')
                print(f"    pair {pair_idx}: {' & '.join(parts)} mismatch")
        elif verbose:
            print(f"  Stage {s}: {len(vecs)} pairs all OK")

    if verbose:
        print(f"\n  IFFT conj(w): {total_ok}/{total_check} OK")

    return total_ok == total_check


# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description='Falcon FFT/IFFT Golden Verification Suite')
    parser.add_argument('--logn', type=int, nargs='+', default=[9],
                        help='logN values (default: 9)')
    parser.add_argument('--mode', choices=['fft', 'ifft', 'both'],
                        default='both', help='Mode to verify')
    parser.add_argument('--full', action='store_true',
                        help='Run full test matrix (all input types)')
    parser.add_argument('--quick', action='store_true',
                        help='Quick smoke test (random only)')
    parser.add_argument('--conj-check', action='store_true',
                        help='Run explicit IFFT conj(w) verification')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Show per-stage details')
    args = parser.parse_args()

    modes = ['fft', 'ifft'] if args.mode == 'both' else [args.mode]

    if args.quick:
        input_types = ['random']
    elif args.full:
        input_types = list(TEST_MATRIX.keys())
    else:
        input_types = ['random', 'impulse', 'falcon_poly', 'all_zeros']

    print("=" * 70)
    print("  Falcon FFT/IFFT Golden Verification Suite")
    print("=" * 70)
    print(f"  logN values: {args.logn}")
    print(f"  modes:       {modes}")
    print(f"  input types: {input_types}")
    if not args.quick:
        print(f"  spike cases: {len(SPIKE_CASES)} positions/values")
    print()

    # Run conj(w) verification
    if args.conj_check or not args.quick:
        for logn in args.logn:
            ok = verify_ifft_conj_twiddle(logn, verbose=args.verbose)
            if not ok:
                print(f"\n  !! IFFT conj(w) check FAILED for logN={logn}")
                return 1

    # Run full suite
    suite = run_test_suite(
        args.logn, modes, input_types, lanes=5, verbose=args.verbose)

    # Summary
    print(f"\n{'='*70}")
    print(f"  VERIFICATION SUMMARY")
    print(f"{'='*70}")

    n_configs = len(suite['results'])
    n_pass = sum(1 for r in suite['results'] if r['all_ok'])

    print(f"  Configurations: {n_configs} total, {n_pass} pass, "
          f"{n_configs - n_pass} fail")
    print(f"  Butterfly operations: {suite['total_passed']}/{suite['total_ops']} passed")

    # Per-config details
    if not suite['all_pass'] or args.verbose:
        print(f"\n  Details:")
        for r in suite['results']:
            status = 'PASS' if r['all_ok'] else 'FAIL'
            print(f"    [{status}] {r['label']} logN={r['logn']}: "
                  f"{r['total_passed']}/{r['total_pairs']} ops OK")

    # Coverage summary
    print(f"\n  Coverage matrix:")
    for logn in args.logn:
        for mode in modes:
            covered = sum(1 for r in suite['results']
                         if r['logn'] == logn and r['inverse'] == (mode == 'ifft'))
            print(f"    logN={logn} {mode.upper():4s}: {covered} test configs")

    if suite['all_pass']:
        print(f"\n  [PASS] All golden vectors verified successfully.")
        print(f"  RTL operator (reconfig_fe_f64) is ready for simulation.")
        return 0
    else:
        print(f"\n  [FAIL] {suite['total_ops'] - suite['total_passed']} mismatches found.")
        return 1


if __name__ == '__main__':
    sys.exit(main())
